### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by kevgrig** [mmazzarolo/react-native-radio-button#3]
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by mmazzarolo** [comment]
this repo in not maintained anymore

**Comment by kevgrig** [comment]
If you could add a license, then people can fork/use it. Without a license, it's unclear.

**Comment by mmazzarolo** [comment]
Added 👍

**Comment by kevgrig** [comment]
Thanks!
